LOGIN = "mjeannin"

PROVIDER  = "libvirt"
VM_MEMORY = 4048
VM_CPUS   = 4

SERVER_IP = "192.168.56.110"
BOX_IMAGE = "debian/bookworm64"

Vagrant.configure("2") do |config|

  config.vm.define "#{LOGIN}S" do |server|
    server.vm.box = BOX_IMAGE
    server.vm.hostname = "#{LOGIN}S"
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider PROVIDER do |vb|
      vb.memory = VM_MEMORY
      vb.cpus = VM_CPUS
    end
    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end

end