LOGIN = "mjeannin"

Vagrant.configure("2") do |config|

  config.vm.define "#{LOGIN}S" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "#{LOGIN}S"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder ".", "/vagrant", type: "rsync"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end
end