Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204" 
  config.vm.hostname = "cgelin-p3"

  config.vm.provider :libvirt do |lv|
    lv.cpus = 2
    lv.memory = 2048
  end

  config.vm.network "private_network", ip: "192.168.56.120"

  config.vm.provision "shell", path: "scripts/bootstrap.sh"
end