
LOGIN = "mjeannin"

PROVIDER    = "virtualbox"
VM_MEMORY   = 4048
VM_CPUS     = 2

SERVER_IP = "192.168.56.120"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204" 
  config.vm.hostname = "#{LOGIN}S"

  config.vm.provider PROVIDER do |lv|
    lv.cpus = "#{VM_CPUS}"
    lv.memory = "#{VM_MEMORY}"
    lv.name = "#{LOGIN}_VM"
  end

  config.vm.network "private_network", ip: "#{SERVER_IP}"

  config.vm.provision "shell", path: "scripts/bootstrap.sh"
end